# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: core-org-builder
email:
description: >- # this means to ignore newlines until "baseurl:"
  dockerized jekyll builder for bitcoincore.org.

twitter_username: bitcoincoreorg
github_username: bitcoin-core
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
#theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - _posts

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# REMINDER - You have to reload the _config.yml for changes to take effect
# press ctrl-c to stop
# SITE=./docs make image
# SITE=./docs make server

author:
  name   : "@BitcoinCoreOrg"
  avatar : "https://avatars.githubusercontent.com/u/13464320?s=200&v=4"
  bio    : "PGP fingerprint: 71A3 B167 3540 5025 D447 E8F2 7481 0B01 2346 C9A6"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://bitcoincore-dev.github.io/core-org-builder/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bitcoincoreorg"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bitcoin-core/core-org-builder"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BitcoinCoreOrg"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bitcoin-core"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

