# This is a basic workflow to help you get started with Actions
name: workflow-matrix

# Controls when the action will run. 
on: [push, pull_request]

jobs:

  github-workspace:
    name: github-workspace
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Print github workspace
        run: |
          printenv

  ubuntu-site-matrix:
    name: github-workspace
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: site-make-image
        run: |
          [[ -d ~/bitcoincore.org ]] || git clone https://github.com/$GITHUB_REPOSITORY_OWNER/bitcoincore.org.git ~/bitcoincore.org
          make help report image profile=bitcoincore-dev


  ruby-ubuntu-matrix:
    name: "ruby-2-5-5/8"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
        ruby:
          - 2.5.5
          - 2.5.8
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: site-make-image
        run: |
          [ -d ~/bitcoincore.org ] || git clone https://github.com/$GITHUB_REPOSITORY_OWNER/bitcoincore.org.git ~/bitcoincore.org
          SITE=~/bitcoincore.org make help report image profile=bitcoincore-dev
        env:
          RUBY_VERSION: ${{ matrix.ruby }}

