# This is a basic workflow to help you get started with Actions
name: workflows

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ubuntu-site-make-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: site-make-image
        run: |
          [[ -d ~/bitcoincore.org ]] || git clone https://github.com/bitcoincore-dev/bitcoincore.org.git ~/bitcoincore.org
          make image

  ubuntu-latest-site-make-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: latest-site-make-image
        run: |
          [[ -d ~/bitcoincore.org ]] || git clone https://github.com/bitcoincore-dev/bitcoincore.org.git ~/bitcoincore.org
          SITE=~/bitcoincore.org make image

  ubuntu20-make-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: make-image
        run: |
          [[ -d ~/bitcoincore.org ]] || git clone https://github.com/bitcoincore-dev/bitcoincore.org.git ~/bitcoincore.org
          make image

  ubuntu20-site-make-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: site-make-image
        run: |
          [[ -d ~/bitcoincore.org ]] || git clone https://github.com/bitcoincore-dev/bitcoincore.org.git ~/bitcoincore.org
          SITE=~/bitcoincore.org make image

  ubuntu18-make-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: make-image
        run: |
          [[ -d ~/bitcoincore.org ]] || git clone https://github.com/bitcoincore-dev/bitcoincore.org.git ~/bitcoincore.org
          make image

  ubuntu18-site-make-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: site-make-image
        run: |
          [[ -d ~/bitcoincore.org ]] || git clone https://github.com/bitcoincore-dev/bitcoincore.org.git ~/bitcoincore.org
          SITE=~/bitcoincore.org make image

  build:
    name: "GitHub Pages Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.5.8
    steps:
      - uses: actions/checkout@v2
      - name: site-make-image
        run: |
          [[ -d ~/bitcoincore.org ]] || git clone https://github.com/bitcoincore-dev/bitcoincore.org.git ~/bitcoincore.org
          SITE=~/bitcoincore.org make image
        env:
          RUBY_VERSION: ${{ matrix.ruby }}

