# This is a basic workflow to help you get started with Actions
name: workflows

# Controls when the action will run. 
on: [push, pull_request]

jobs:

  github-workspace:
    name: make matrix latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: make submodules image server
        run: |
          printenv
          make submodules
          SITE=./bitcoincore.org make image
          #SITE=./bitcoincore.org make server

  ruby-2-5-5-8:
    name: "ruby-2-5-5/8"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.5.5
          - 2.5.8
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: site-make-image
        run: |
          make submodules
          SITE=./bitcoincore.org make image
          #SITE=./bitcoincore.org make server
        env:
          RUBY_VERSION: ${{ matrix.ruby }}

